// common mutation
export const SWITCH_SIDEBAR_COLLAPSE = 'SWITCH_SIDEBAR_COLLAPSE'
export const UPDATE_DOCUMENT_CLIENT_HEIGHT = 'UPDATE_DOCUMENT_CLIENT_HEIGHT'

// menu mutations
export const SET_MENU_NAV_LIST = 'SET_MENU_NAV_LIST'
export const SET_PERMISSIONS = 'SET_PERMISSIONS'
export const UPDATE_MENU_NAV_ACTIVE_NAME = 'UPDATE_MENU_NAV_ACTIVE_NAME'

// tabs mutations
export const UPDATE_TABS_ACTIVE_NAME = 'UPDATE_TABS_ACTIVE_NAME'
export const CLEAR_TABS_NAV_LIST = 'CLEAR_TABS_NAV_LIST'
export const ADD_TABS_NAV_LIST = 'ADD_TABS_NAV_LIST'
export const DEL_TABS_NAV_LIST = 'DEL_TABS_NAV_LIST'

export const CLOSE_OTHER_TABS_NAV_LIST = 'CLOSE_OTHER_TABS_NAV_LIST'
export const CLOSE_LEFT_TABS_NAV_LIST = 'CLOSE_LEFT_TABS_NAV_LIST'
export const CLOSE_RIGHT_TABS_NAV_LIST = 'CLOSE_RIGHT_TABS_NAV_LIST'

// user mutations
export const SET_TOKEN = 'SET_TOKEN'
export const SET_UID = 'SET_UID'
export const SET_INTRODUCTION = 'SET_INTRODUCTION'
export const SET_NAME = 'SET_NAME'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_USER_INFO = 'SET_USER_INFO'
